### ISSUE TITLE
Migrating to a monorepo

### ISSUE THREAD

**Issue by ubermanu** [stylelint-less/stylelint-config-standard-less#1]
Hey Crazy Urus,

I sent you an email earlier about my project of migrating all the `stylelint-less` repositories into a single organisation

I asked Sivanatarajan the same for both `stylelint-less` and `stylelint-config-recommended-less`

This is what I have actually: https://github.com/stylelint-less/stylelint-less

Hit me up if you are interested!

**Comment by crazyurus** [comment]
@ubermanu I agree that it has been transferred to this organization `style-less`. I hope we can maintain it well.

**Comment by ubermanu** [comment]
Nice!

I'm waiting for @ssivanatarajan to hop in for the 2 other repos, I'll keep you in touch

**Comment by SevenOutman** [comment]
Glad to see the tooling gets united! Maybe also involve options from @less org about Less specific rules.
